### ISSUE TITLE
Research/buy bed frame for guest room

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#16]
Queen size, unless we realize after getting the one from #7 that it's too big for that room.

**Comment by ChrissyMoo** [comment]
Purchased Queen Bed Frame from Ikea - Tarva.

Modified Headboard as per this tutorial:  http://www.adesignerathome.com/how-i-made-it-mid-century-inspired-ikea-tarva-bed-hack/
