### ISSUE TITLE
Things to buy from Ikea

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#17]
- [ ] Hex mirrors for guest room
- [x] Wardrobe for guest room (#15)
- [x] 2 Stools for kitchen island, to match existing
- [x] More drawers/fittings for master closet (@ChrissyMoo) to determine in another ticket
- [x] Garbage/recycling bins?
- [x] Kitchen utensil organizers?
- [x] Spice rack and jars for drawers
- [ ] Cabinet for above guest bathroom door?
- [x] Door for kitchen island- 15"?
  Also, return unneeded kitchen parts, if any (receipt hopefully in black file folder)

**Comment by ChrissyMoo** [comment]
Made Ikea trip on October 22 - purchased some items from list.

**Comment by ChrissyMoo** [comment]
Hex Mirrors are no longer available :(

Nixed Idea for Cabinet above guest bathroom door.
