### ISSUE TITLE
Hang bikes from ceiling

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#19]
Where in the apartment? What hardware is required?

**Comment by ChrissyMoo** [comment]
Alan Completed!!!!!

Bike Rack/pulley system perched from Amazon.

Gear Up Up and Away Deluxe Hoist System
https://www.amazon.com/gp/product/B0002TPTSW/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1
