### ISSUE TITLE
Buy shower curtain for guest bathroom + Install Rod

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#20]

**Comment by ChrissyMoo** [comment]
Shower Curtain Options for guest room:

https://society6.com/product/gold-marble-sgm_shower-curtain#s6-3330935p34a35v287

https://society6.com/product/black--gold-sparkle-tjt_shower-curtain#s6-3950274p34a35v287

**Comment by ChrissyMoo** [comment]
Shower Curtain + Rings purchased from Target.
