### ISSUE TITLE
Buy a skinny shower curtain & rod

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#28]

**Comment by ChrissyMoo** [comment]
Shower Curtain Options:

https://www.amazon.com/Sfoothome-Eco-friendly-Resistant-Waterproof-Cobblestone/dp/B01IEAEGA2/ref=sr_1_90?s=home-garden&ie=UTF8&qid=1476996089&sr=1-90&keywords=shower%2Bcurtain%2Bshower%2Bstall&th=1

**Comment by ChrissyMoo** [comment]
Ordered Shower Curtain + Rod + Shower Curtain Rings from Amazon - Will arrive on Wed 11-23-16.
