### ISSUE TITLE
Make curtains for main space windows

### ISSUE THREAD

**Issue by alanmoo** [alanmoo/Sparkle-Moose-Lounge#51]

**Comment by ChrissyMoo** [comment]
Tension Rods are up.  Measure and see how many windows I can get with Birdcage Fabric.

Buy Backing Fabric to use with birdcage fabric.  Solid Natural Color Fabric.

**Comment by ChrissyMoo** [comment]
Purchased Lining Fabric.  

Birdcage fabric will work for 2 windows (x1.5 fullness)

**Comment by ChrissyMoo** [comment]
Ditched Idea of making curtains. 

Purchased Curtains from Target:  Cloud Island (baby collection) Gray w/ Trees
