### ISSUE TITLE
Research/Buy Plush Wool Topper for King Mattress

### ISSUE THREAD

**Issue by ChrissyMoo** [alanmoo/Sparkle-Moose-Lounge#55]
Look up the one we tried at the Clean Bedroom.

Holy Lamb Organics Ultimate Mattress Topper ($794 for King from Clean Bedroom)

https://www.amazon.com/Holy-Lamb-Organics-Ultimate-Mattress/dp/B0050DYM74?th=1

**Comment by alanmoo** [comment]
Got it! It's nice!
