### ISSUE TITLE
Buy Pillows that Don't Suck

### ISSUE THREAD

**Issue by ChrissyMoo** [alanmoo/Sparkle-Moose-Lounge#56]
Ones we loved from the clean bedroom:

Alan:  Sachi Organics Rejuvenation Millet Pillow (Large 14.5x20)  96.99 at Clean Bedroom

https://www.amazon.com/Serenity-Rejuvenation-Organic-Eco-Wool-Pillowcase/dp/B00PD7NUGQ/ref=pd_lpo_121_tr_t_3?_encoding=UTF8&psc=1&refRID=K89W3B5ZHA7XWDPGMJ9F

Christine:  Green Sleep Ergo 6500 Pillows (King)

**Comment by alanmoo** [comment]
Turns out the IKEA pillows are pretty damn good. [JORDRÖK Firmer](http://www.ikea.com/ca/en/catalog/products/50269618/#/40269614)
